Add support paths with numbers
MaloPolese/copy-json-path pull request #25
Opened 2024-12-12 15:31 UTC by fcsonline

We have discovered that some specific paths are not properly build.

If your JSON content is something like:

```json
{
  "foo": {
       "bar2": "baz"
   }
}
```

The exported json path is `foo.["bar2"]`. This commit solves this issue.

2024-12-12 16:40 UTC, MaloPolese requested changes
Hello, 
Thanks for your PR! :heart: 
Your code looks good to me. However, tests fail with this new rule.

For example, the test: “getJsonPath test characters without escaping from allowed ranges' ” fails.
And the charactersWithoutEscaping variable needs to be updated with numbers now.

Can you adapt the tests to your PR?

2024-12-12 16:40 UTC, MaloPolese commented on src/json.path.ts
> +    return true
```suggestion
    return true;
```
Just to be consistent with the code base :sweat_smile:

2024-12-12 17:17 UTC, fcsonline commented
Let me fix them

2024-12-12 17:29 UTC, fcsonline commented
I executed the test suite and it looks ok:

```
Testing range 'ø-ÿ' char: 'ý', index: 253
Testing range 'ø-ÿ' char: 'þ', index: 254
Testing range 'ø-ÿ' char: 'ÿ', index: 255
    ✔ getJsonPath test characters without escaping from allowed ranges

[31748:1212/182728.107966:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.

    ✔ getJsonPath test change quote type

[31748:1212/182728.987754:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.

[31748:1212/182729.018497:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.

[31748:1212/182729.113142:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.

  6 passing (2s)

[main 2024-12-12T17:27:29.248Z] Extension host with pid 32743 exited with code: 0, signal: unknown.

```

Btw, I had to update the typescript dependency to avoid this error:

```
node_modules/@types/har-format/index.d.ts:258:6 - error TS1023: An index signature parameter type must be either 'string' or 'number'.
```

2024-12-12 18:19 UTC, fcsonline commented
@MaloPolese Sorry, I'm unable to understand those tests 😅 They are testing one single character at a time. My case is different. One single digit, should be escaped, but a string like "foo2" can be plain.

2024-12-12 18:48 UTC, MaloPolese commented
Hmmm yes I see, the tests are a bit weird. I'll take a look this weekend :+1:

2024-12-13 07:10 UTC, fcsonline commented
Thank you for handling those tests! 

And thank you again for all your time invested in this extension! 👏

2024-12-21 17:29 UTC, merged